modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="gstamina"
version="0.0.2"
displayName="Glebun08's Stamina"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Glebun08, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.gstamina]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration