modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="gstamina"
version="0.0.0"
displayName="Glebun08's Stamina"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Glebun08, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.gstamina]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.gstamina]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.gstamina]]
    modId="createnew"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration